In [2]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [3]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



Task 1: Zigzag Walk

In [3]:
def walk_zigzag(floor):
  rows,cols= floor.shape
  for i in range(cols):
    if i%2!= 0:
      for j in range(rows-1, 0, -1):
        if j%2!=0:
          print(floor[j][i], end=' ')
      print()
    else:
      for k in range(0, rows, 1):
        if k%2==0:
          print(floor[k][i], end=' ')
      print()

floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
# print('################')
# floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
#                   ['7' , '2' , '1' , '9' , '3'],
#                   ['9' , '0' , '7' , '5' , '8'],
#                   ['2' , '1' , '3' , '4' , '0']]
#                 )

# print_matrix(floor)
# print('Walking Sequence:')
# walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 


Task 2: Row Rotation Policy of BRACU Classroom

In [4]:
def row_rotation(exam_week, seat_status):
  row,column = seat_status.shape
  count = 0
  for i in range(exam_week+1):
    count+=1
    for j in range(column):
      value = seat_status[0][j]
      for k in range(row-1):
        seat_status[k][j] = seat_status[k+1][j]
      seat_status[row-1][j] = value

  print_matrix(seat_status)
  return count//2

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number= row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------
|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
Your friend AA will be on row 2


Task 3: Matrix Manipulation

In [5]:
def reverse_Matrix(matrix):
  row,column = matrix.shape
  final = np.zeros(matrix.shape,dtype=int)

  for i in range(row):
    for j in range(column):

      if row-i<=row and column-j <= column:
        value = matrix[i][j]
        final[i][j]  = matrix[(row-1)-i][(column-1)-j]
        final[(row-1)-i][(column-1)-j] = value

  return final

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print_matrix(matrix)
print('# =====================')
print('Reversed Matrix is:')
print()
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------


|  14 |  8  |  0  |  4  |
-------------------------
|  9  |  8  |  13 |  13 |
-------------------------
|  9  |  3  |  1  |  4  |
-------------------------
|  2  |  10 |  13 |  6  |
-------------------------
# =====================
Reversed Matrix is:

|  6  |  13 |  10 |  2  |
-------------------------
|  4  |  1  |  3  |  9  |
-------------------------
|  13 |  13 |  8  |  9  |
-------------------------
|  4  |  0  |  8  |  14 |
-------------------------


Task 4: Chess Piece

In [6]:
def show_knight_move(knight):

  arr = np.zeros((8,8),dtype=int)
  x , y = knight #3,4
  arr[x][y] = 66
  moves = np.array([[-2,1],[-2,-1],[2,-1],[2,1],[-1,-2],[-1,2],[1,2],[1,-2]])
  for i in moves:
    p , q =i[0] , i[1]
    #print(p,q)
    if x + p < 8 and y + q < 8:
      arr[x+p][y+q] = 3

  return arr



knight = (3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#-----------------------------------------

|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  3  |  0  |  3  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  3  |  0  |  0  |  0  |  3  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  66 |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  3  |  0  |  0  |  0  |  3  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  3  |  0  |  3  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------
|  0  |  0  |  0  |  0  |  0  |  0  |  0  |  0  |
-------------------------------------------------


Task 5: Matrix Compression

In [7]:
def compress_matrix(matrix):
  final = np.zeros((2,2),dtype=int)
  row,column = matrix.shape

  for i in range(0,row,2):
    for j in range(0,column,2):
      sum = matrix[i][j] + matrix[i+1][j] + matrix[i][j+1] + matrix[i+1][j+1]
      final[i//2][j//2] = sum
  return final

matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
returned_array= compress_matrix(matrix)
print('Answer is: ')
print()
print_matrix(returned_array)
#This should print
#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

|  1  |  2  |  3  |  4  |
-------------------------
|  5  |  6  |  7  |  8  |
-------------------------
|  1  |  3  |  5  |  2  |
-------------------------
|  -2 |  0  |  6  |  -3 |
-------------------------
Answer is: 

|  14 |  22 |
-------------
|  2  |  10 |
-------------


Task 6: Game Arena

In [8]:
def play_game(arena):
  row,column = arena.shape
  moves = np.array([[1,0],[0,1],[-1,0],[0,-1]])
  count = 0
  for i in range(row):
    for j in range(column):
      if arena[i][j] % 50 == 0 and arena[i][j] > 0:

        for k in moves:
          x,y = k
          if i+x < row and j+y < column:
            if arena[i+x][j+y] == 2:
              count+=1

  total_points = count*2
  if total_points > 10:
    print(f"Points Gained: {total_points}. Your team has survived the game.")
  else:
    print(f"Points Gained: {total_points}. Your team is out. ")
#=============================================================================
arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

|  0  |  2  |  2  |  0  |
-------------------------
|  50 |  1  |  2  |  0  |
-------------------------
|  2  |  2  |  2  |  0  |
-------------------------
|  1  |  100 |  2  |  0  |
-------------------------
Points Gained: 6. Your team is out. 
.....................
|  0  |  2  |  2  |  0  |  2  |
-------------------------------
|  1  |  50 |  2  |  1  |  100 |
-------------------------------
|  2  |  2  |  2  |  0  |  2  |
-------------------------------
|  0  |  200 |  2  |  0  |  0  |
-------------------------------
Points Gained: 14. Your team has survived the game.


Bonus Task: Primary vs Secondary Diagonal

In [27]:
def check_Diagonal(matrix1, matrix2):
  r1,c1 = matrix1.shape
  r2,c2 = matrix2.shape
  arr1 = np.array([0]*r1)
  arr2 = np.array([0]*r2)

  c= c1
  idx= 0
  for i in range(r1):
    arr1[idx] = matrix1[i][c-1]
    c-= 1
    idx+=1
  print(arr1)

  c= 0
  idx= 0
  for i in range(r2):
    arr2[idx] = matrix2[i][c]
    c+= 1
    idx+=1
  print(arr2)

  count = 0
  for k in arr1:
    if k in arr2:
      count+=1
  if count == r1 and count == r2:
    print('YES')
  else:
    print('NO')

array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])

check_Diagonal(array1, array2) #This should print YES
print(".............")
array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])

check_Diagonal (array1, array2) #This should print NO

[1 2 3]
[3 2 1]
YES
.............
[1 2 3 4]
[4 0 2 1]
NO
